export const handleHome = (req, res) => res.send('Your in Home')
export const editVideos = (req, res) => res.send('Edit Videos')
export const seeVideos = (req, res) => res.send('See Videos')
export const search = (req, res)=> res.send("Search")
export const upload = (req, res) => res.send('Upload Videos')
export const deleteVideos = (req, res) => res.send('Delete Videos')
